### PR TITLE
fix: Can't resolve '@iconify/json/package.json' error

### LINKED ISSUE #9: Tailwind CSS: Can't resolve '@iconify/json/package.json'
It will break the vs code Tailwind CSS IntelliSense

image

Here is the Tailwind config

```
const { iconsPlugin, getIconCollections } = require('@egoist/tailwindcss-icons')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',

    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
    iconsPlugin({
      collections: getIconCollections(['radix-icons']),
    }),
  ],
}

```
And installed `@iconify-json/radix-icons`

image

After installing `@iconify/json` the problem is gone.

### PR DESCRIPTION
**Pull request by sinchang**
Fixes #9

### CODE REVIEW

File: src/core.ts [hunk 1]
```diff
@@ -17,7 +17,8 @@ export const localResolve = (cwd: string, id: string) => {
     const resolved = req.resolve(id, { paths: [cwd] })
     return resolved
   } catch (error: any) {
-    if (error.code === "MODULE_NOT_FOUND") return null
+    if (error.code === "MODULE_NOT_FOUND" || require.main !== module)
+      return null
```
Comment (egoist) [inline src/core.ts]: i think we can just return null for all errors
